---
title: "HW6"
output: html_notebook
---

```{r}
#1
47/863
(47/863)*100

p_hat <- 47/863

z <- 1.645

ME <- 1.645 * sqrt((p_hat*(1-p_hat))/863)
ME

p_hat - ME
p_hat + ME

```

```{r}
#2
s_mean <- 108
p_sd <- 13

n <- 25

z <- 2.05

ME <- 2.05*(13/(sqrt(25)))
ME

s_mean - ME
s_mean + ME
#################
n <- 10

ME <- z*(13/(sqrt(n)))
ME

s_mean - ME
s_mean + ME
########################

n <- 25

z <- 2.05

ME <- z*(13/(sqrt(n)))
ME

s_mean - ME
s_mean + ME
###################################
n <- 25

z <- 1.555

ME <- z*(13/(sqrt(n)))
ME

s_mean - ME
s_mean + ME


```

```{r}
#3

exercise <- c(2,7,2,4,1,5,4,3,5,1,0,1,6,4,2,1,3,0,2,7,2,4,2,0,1,5,3,1,7,0,4,7)

mean <- mean(exercise)

n <- 32

sd <- sd(exercise)

t <- 2.04

ME <- t*(sd/sqrt(n))
ME

mean - ME
mean + ME

```

```{r}
#4

z <- 2.58
sd <- 13.4
ME <- 2

n <- ((z*sd)/ME)^2
n
#####################
z <- 1.96
sd <- 13.4
ME <- 2

n <- ((z*sd)/ME)^2
n


```

```{r}
#5

p <- 0.69
q <- 1 - 0.69
ME <- 0.03

z <- 2.58

n <- ((z^2)*p*q)/(ME^2)
n
###########################
p <- 0.5
q <- 1 - 0.5
ME <- 0.03

z <- 2.58

n <- ((z^2)*p*q)/(ME^2)
n


```

